#!/usr/bin/env python3
import os
import sys
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

fireFoxOptions = webdriver.FirefoxOptions()
fireFoxOptions.set_headless()
fireFoxOptions.set_preference('network.proxy.type', 0);

def connected(browser):
    if browser.find_elements('id', 'usage_flux') != []:
        return True
    else:
        return False

def connect(browser, username, password):
    url = browser.current_url
    if connected(browser):
        print('Connected already')
        return  
    input_username = browser.find_element('id', 'username')
    input_password = browser.find_element('id', 'password')
    input_connect = browser.find_element('id', 'connect')
    input_username.send_keys(username)
    input_password.send_keys(password)
    input_connect.click()
    time.sleep(1)
    if connected(browser):
        print('Connection succeed')
    else:
        print('Connection fail')

def disconnect(browser):
    # browser.get('http://auth4.tsinghua.edu.cn')
    if connected(browser):
        browser.find_element(By.XPATH, '//button[@class="disconnect"]').click()
    if connected(browser):
        print('Disconnected')

if __name__ == '__main__':
    browser = webdriver.Firefox(firefox_options=fireFoxOptions);
    # get username, password
    userinfofilename = os.path.expanduser('~/.TsinghuaNet/netTHUAuth')
    if not os.path.exists(os.path.dirname(userinfofilename)):
        os.makedirs(os.path.dirname(userinfofilename))
    if not os.path.exists(userinfofilename):
        username = input('username')
        password = input('password')
        userinfo = {'username': username, 'password': password}
        with open(userinfofilename, 'w') as fd:
            json.dump(userinfo, fd)
    with open(userinfofilename) as fd:
        userinfo = json.load(fd)
        username = userinfo['username']
        password = userinfo['password']
    for url in ['http://auth4.tsinghua.edu.cn', 'http://auth6.tsinghua.edu.cn']:
        print('Connecting', url)
        browser.get(url)
        if '-o' in sys.argv:
            disconnect(browser)
        else:
            connect(browser, username, password)
        if EC.alert_is_present()(browser):
            print(browser.switch_to_alert().text)
            browser.switch_to_alert().accept()
        print()
    cmd = '* * * * *  ping -c 1 -W 1 info.tsinghua.edu.cn >/dev/null 2>&1 || ' + os.path.abspath(__file__)
    print('you can add the following to your crontab')
    print(cmd)
    browser.close()



